name: C CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure environment variables
        run: ./configure
      - name: Build test application
        run: make
      - name: Run tests
        run: make test

